default: all
Q0 : Q0.c
	gcc -Wall -ansi -o Q0 Q0.c
Q1 : Q1.c
	gcc -Wall -ansi -o Q1 Q1.c
Q2 : Q2.c
	gcc -Wall -ansi -o Q2 Q2.c
Q3 : Q3.c
	gcc -Wall -ansi -o Q3 Q3.c
Q4 : Q4.c
	gcc -Wall -ansi -o Q4 Q4.c
Q5 : Q5.c
	gcc -Wall -ansi -o Q5 Q5.c
all:
	gcc -Wall -ansi -o Q0 Q0.c
	gcc -Wall -ansi -o Q1 Q1.c
	gcc -Wall -ansi -o Q2 Q2.c
	gcc -Wall -ansi -o Q3 Q3.c
	gcc -Wall -ansi -o Q4 Q4.c
	gcc -Wall -ansi -o Q5 Q5.c

